class Country {
    constructor(name, region) {
        this.name = name;
        this.region = region;
    }
}
  
const countries = [
    new Country('Afghanistan', 'Asia'),
    new Country('Albania', 'Europe'),
    new Country('Algeria', 'Africa'),
    new Country('Andorra', 'Europe'),
    new Country('Angola', 'Africa'),
    new Country('Antigua and Barbuda', 'North America'),
    new Country('Argentina', 'South America'),
    new Country('Armenia', 'Asia'),
    new Country('Australia', 'Oceania'),
    new Country('Austria', 'Europe'),
    new Country('Azerbaijan', 'Asia'),
    new Country('Bahamas', 'North America'),
    new Country('Bahrain', 'Asia'),
    new Country('Bangladesh', 'Asia'),
    new Country('Barbados', 'North America'),
    new Country('Belarus', 'Europe'),
    new Country('Belgium', 'Europe'),
    new Country('Belize', 'North America'),
    new Country('Benin', 'Africa'),
    new Country('Bhutan', 'Asia'),
    new Country('Bolivia', 'South America'),
    new Country('Bosnia and Herzegovina', 'Europe'),
    new Country('Botswana', 'Africa'),
    new Country('Brazil', 'South America'),
    new Country('Brunei', 'Asia'),
    new Country('Bulgaria', 'Europe'),
    new Country('Burkina Faso', 'Africa'),
    new Country('Burundi', 'Africa'),
    new Country('Cabo Verde', 'Africa'),
    new Country('Cambodia', 'Asia'),
    new Country('Cameroon', 'Africa'),
    new Country('Canada', 'North America'),
    new Country('Central African Republic', 'Africa'),
    new Country('Chad', 'Africa'),
    new Country('Chile', 'South America'),
    new Country('China', 'Asia'),
    new Country('Colombia', 'South America'),
    new Country('Comoros', 'Africa'),
    new Country('Congo (Brazzaville)', 'Africa'),
    new Country('Congo (Kinshasa)', 'Africa'),
    new Country('Costa Rica', 'North America'),
    new Country('Croatia', 'Europe'),
    new Country('Cuba', 'North America'),
    new Country('Cyprus', 'Asia'),
    new Country('Czech Republic', 'Europe'),
    new Country('Denmark', 'Europe'),
    new Country('Djibouti', 'Africa'),
    new Country('Dominica', 'North America'),
    new Country('Dominican Republic', 'North America'),
    new Country('Ecuador', 'South America'),
    new Country('Egypt', 'Africa'),
    new Country('El Salvador', 'North America'),
    new Country('Equatorial Guinea', 'Africa'),
    new Country('Eritrea', 'Africa'),
    new Country('Estonia', 'Europe'),
    new Country('Eswatini', 'Africa'),
    new Country('Ethiopia', 'Africa'),
    new Country('Fiji', 'Oceania'),
    new Country('Finland', 'Europe'),
    new Country('France', 'Europe'),
    new Country('Gabon', 'Africa'),
    new Country('Gambia', 'Africa'),
    new Country('Georgia', 'Asia'),
    new Country('Germany', 'Europe'),
    new Country('Ghana', 'Africa'),
    new Country('Greece', 'Europe'),
    new Country('Grenada', 'North America'),
    new Country('Guatemala', 'North America'),
    new Country('Guinea', 'Africa'),
    new Country('Guinea-Bissau', 'Africa'),
    new Country('Guyana', 'South America'),
    new Country('Haiti', 'North America'),
    new Country('Holy See', 'Europe'),
    new Country('Honduras', 'North America'),
    new Country('Hungary', 'Europe'),
    new Country('Iceland', 'Europe'),
    new Country('India', 'Asia'),
    new Country('Indonesia', 'Asia'),
    new Country('Iran', 'Asia'),
    new Country('Iraq', 'Asia'),
    new Country('Ireland', 'Europe'),
    new Country('Israel', 'Asia'),
    new Country('Italy', 'Europe'),
    new Country('Jamaica', 'North America'),
    new Country('Japan', 'Asia'),
    new Country('Jordan', 'Asia'),
    new Country('Kazakhstan', 'Asia'),
    new Country('Kenya', 'Africa'),
    new Country('Kiribati', 'Oceania'),
    new Country('Korea, South', 'Asia'),
    new Country('Kosovo', 'Europe'),
    new Country('Kuwait', 'Asia'),
    new Country('Kyrgyzstan', 'Asia'),
    new Country('Laos', 'Asia'),
    new Country('Latvia', 'Europe'),
    new Country('Lebanon', 'Asia'),
    new Country('Lesotho', 'Africa'),
    new Country('Liberia', 'Africa'),
    new Country('Libya', 'Africa'),
    new Country('Liechtenstein', 'Europe'),
    new Country('Lithuania', 'Europe'),
    new Country('Luxembourg', 'Europe'),
    new Country('Madagascar', 'Africa'),
    new Country('Malawi', 'Africa'),
    new Country('Malaysia', 'Asia'),
    new Country('Maldives', 'Asia'),
    new Country('Mali', 'Africa'),
    new Country('Malta', 'Europe'),
    new Country('Marshall Islands', 'Oceania'),
    new Country('Mauritania', 'Africa'),
    new Country('Mauritius', 'Africa'),
    new Country('Mexico', 'North America'),
    new Country('Micronesia', 'Oceania'),
    new Country('Moldova', 'Europe'),
    new Country('Monaco', 'Europe'),
    new Country('Mongolia', 'Asia'),
    new Country('Montenegro', 'Europe'),
    new Country('Morocco', 'Africa'),
    new Country('Mozambique', 'Africa'),
    new Country('Myanmar', 'Asia'),
    new Country('Namibia', 'Africa'),
    new Country('Nauru', 'Oceania'),
    new Country('Nepal', 'Asia'),
    new Country('Netherlands', 'Europe'),
    new Country('New Zealand', 'Oceania'),
    new Country('Nicaragua', 'North America'),
    new Country('Niger', 'Africa'),
    new Country('Nigeria', 'Africa'),
    new Country('North Macedonia', 'Europe'),
    new Country('Norway', 'Europe'),
    new Country('Oman', 'Asia'),
    new Country('Pakistan', 'Asia'),
    new Country('Palau', 'Oceania'),
    new Country('Palestine State', 'Asia'),
    new Country('Panama', 'North America'),
    new Country('Papua New Guinea', 'Oceania'),
    new Country('Paraguay', 'South America'),
    new Country('Peru', 'South America'),
    new Country('Philippines', 'Asia'),
    new Country('Poland', 'Europe'),
    new Country('Portugal', 'Europe'),
    new Country('Qatar', 'Asia'),
    new Country('Romania', 'Europe'),
    new Country('Russia', 'Europe'),
    new Country('Rwanda', 'Africa'),
    new Country('Saint Kitts and Nevis', 'North America'),
    new Country('Saint Lucia', 'North America'),
    new Country('Saint Vincent and the Grenadines', 'North America'),
    new Country('Samoa', 'Oceania'),
    new Country('San Marino', 'Europe'),
    new Country('Sao Tome and Principe', 'Africa'),
    new Country('Saudi Arabia', 'Asia'),
    new Country('Senegal', 'Africa'),
    new Country('Serbia', 'Europe'),
    new Country('Seychelles', 'Africa'),
    new Country('Sierra Leone', 'Africa'),
    new Country('Singapore', 'Asia'),
    new Country('Slovakia', 'Europe'),
    new Country('Slovenia', 'Europe'),
    new Country('Solomon Islands', 'Oceania'),
    new Country('Somalia', 'Africa'),
    new Country('South Africa', 'Africa'),
    new Country('South Sudan', 'Africa'),
    new Country('Spain', 'Europe'),
    new Country('Sri Lanka', 'Asia'),
    new Country('Sudan', 'Africa'),
    new Country('Suriname', 'South America'),
    new Country('Sweden', 'Europe'),
    new Country('Switzerland', 'Europe'),
    new Country('Syria', 'Asia'),
    new Country('Taiwan*', 'Asia'),
    new Country('Tajikistan', 'Asia'),
    new Country('Tanzania', 'Africa'),
    new Country('Thailand', 'Asia'),
    new Country('Timor-Leste', 'Asia'),
    new Country('Togo', 'Africa'),
    new Country('Tonga', 'Oceania'),
    new Country('Trinidad and Tobago', 'North America'),
    new Country('Tunisia', 'Africa'),
    new Country('Turkey', 'Asia'),
    new Country('Turkmenistan', 'Asia'),
    new Country('Tuvalu', 'Oceania'),
    new Country('Uganda', 'Africa'),
    new Country('Ukraine', 'Europe'),
    new Country('United Arab Emirates', 'Asia'),
    new Country('United Kingdom', 'Europe'),
    new Country('United States of America', 'North America'),
    new Country('Uruguay', 'South America'),
    new Country('Uzbekistan', 'Asia'),
    new Country('Vanuatu', 'Oceania'),
    new Country('Venezuela', 'South America'),
    new Country('Vietnam', 'Asia'),
    new Country('Yemen', 'Asia'),
    new Country('Zambia', 'Africa'),
    new Country('Zimbabwe', 'Africa'),
];

module.exports = countries;